### ISSUE TITLE
IfPortNot vs IfNotPort?

### ISSUE THREAD

**Issue by RobThree** [amantinband/throw#63]
Hi!

Came here from [your video](https://www.youtube.com/watch?v=l9b8ghprj9I). Nice work, this looks great.

Going thru the README I noticed this:

![image](https://user-images.githubusercontent.com/607888/188514729-4caa6abd-12cf-4cfd-ad5d-c9180fac2ac7.png)

There's this pattern: `IfFoo(...)` -> `IfNotFoo(...)`, `IfBar(...)` -> `IfNotBar(...)`. And then there's `IfPort(...)` -> `IfPortNot(...)`. Not being a native english speaker, I think that maybe the fluent syntax makes for better english ("if port not 8080" v.s. "if not port 8080") but I'm not sure on this. If it's all the same then I would personally opt to rename `IfPortNot(...)` to `IfNotPort(...)`. Just my $0.02.

I'm looking forward to toy a little with this library and maybe eventually decide to use it in actual projects. Again: good work from what I've seen so far! Keep it up!

**Comment by amantinband** [comment]
Hey Rob! Sorry for the late response. I finally had some time to give this repo some love. At first, I wanted the fluent syntax of `IfPortNot(8080)`, but this doesn't work with `IfNotHttp()` for example (`IfHttpNot`?). I ended up going with IfNotX for consistency across all new negations (and didn't update the previous ones for BC)
